import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RoomProvider } from "@/components/room-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const endpoint = `${
		process.env.NODE_ENV === "development" ? "ws" : "wss"
	}://${process.env.NEXT_PUBLIC_SOCKET_HOST}/connect`;
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <RoomProvider endpoint={endpoint}>
          {children}
        </RoomProvider>
      </body>
    </html>
  );
}
