import { ContentLayout } from "@/components/content-layout";

export function TermsOfService() {
	return (
		<ContentLayout title="Terms of Service" lastUpdated="November 24, 2024">
			<h2>1. Acceptance of Terms</h2>
			<p>
				By accessing and using Sketch with Friends (the "Service") provided by
				WalaGames ("we," "us," or "our"), you agree to be bound by these Terms
				of Service ("Terms"). If you do not agree to these Terms, do not use the
				Service.
			</p>

			<h2>2. Description of Service</h2>
			<p>
				The Service provides an online multiplayer drawing and guessing game
				where users can create or join game rooms, draw pictures, guess words,
				and communicate with other users. Players take turns drawing while
				others attempt to guess the word, earning points based on their
				performance.
			</p>

			<h2>3. Game Rules and Fair Play</h2>
			<p>Users agree to follow these basic game rules:</p>
			<h3>3.1 Drawing Rules</h3>
			<ul>
				<li>No intentionally drawing inappropriate or offensive content</li>
				<li>No using external drawing tools or aids</li>
			</ul>

			<h3>3.2 Guessing Rules</h3>
			<ul>
				<li>No using external tools to determine the answer</li>
				<li>No coordinating with other players to manipulate scoring</li>
			</ul>

			<h3>3.3 Chat Behavior</h3>
			<ul>
				<li>No harassment or bullying of other players</li>
				<li>No sharing personal information</li>
				<li>No advertising or promotional content</li>
			</ul>

			<h3>3.4 Technical Fair Play</h3>
			<ul>
				<li>No use of automated tools, bots, or scripts</li>
				<li>No exploiting bugs or glitches</li>
				<li>No intentionally causing lag or performance issues</li>
				<li>No attempting to hack or modify the game client</li>
			</ul>

			<h3>3.5 Room Conduct</h3>
			<ul>
				<li>No intentionally delaying game progress</li>
				<li>No leaving repeatedly to disrupt gameplay</li>
			</ul>

			<p>
				Violation of these rules may result in temporary or permanent suspension
				from the Service. WalaGames reserves the right to determine what
				constitutes a rule violation and to enforce these rules at its
				discretion.
			</p>

			<h2>5. Eligibility</h2>
			<p>
				You must be at least 13 years old to use the Service. By using the
				Service, you represent and warrant that you are at least 13 years of
				age.
			</p>

			<h2>6. User Conduct</h2>
			<p>
				You agree to use the Service in accordance with these Terms and all
				applicable laws. You agree not to:
			</p>
			<ul>
				<li>
					Post or transmit any unlawful, threatening, abusive, hateful,
					defamatory, or otherwise offensive content
				</li>
				<li>
					Violate any third-party rights, including intellectual property rights
				</li>
				<li>Attempt to circumvent any security features of the Service</li>
				<li>Use the Service for any commercial purpose without our consent</li>
				<li>Interfere with or disrupt the Service or servers</li>
				<li>Impersonate any person or entity</li>
			</ul>

			<h2>7. User-Generated Content</h2>
			<h3>7.1 Content Responsibility</h3>
			<p>
				You are solely responsible for any content you create, share, or
				transmit through the Service, including drawings and chat messages. We
				do not claim ownership of your content, but you grant us the right to
				display and transmit it through the Service.
			</p>

			<h3>7.2 Content Disclaimer</h3>
			<p>
				We do not monitor or control user-generated content and are not
				responsible for any content created or shared by users. We are not
				liable for any offensive, inappropriate, or illegal content generated by
				users.
			</p>

			<h2>8. Disclaimers</h2>
			<h3>8.1 Service Provided "As Is"</h3>
			<p>
				The Service is provided on an "as is" and "as available" basis, without
				any warranties of any kind, express or implied.
			</p>

			<h3>8.2 No Liability</h3>
			<p>WalaGames is not liable for any damages arising from:</p>
			<ul>
				<li>Use or inability to use the Service</li>
				<li>Content generated or shared by users</li>
				<li>Technical issues or interruptions in service</li>
				<li>Any unauthorized access to or use of our servers</li>
			</ul>

			<h2>9. Limitation of Liability</h2>
			<p>
				To the maximum extent permitted by law, WalaGames shall not be liable
				for any indirect, incidental, special, consequential, or punitive
				damages arising out of or relating to your use of the Service.
			</p>

			<h2>10. Modifications to Service</h2>
			<p>
				We reserve the right to modify or discontinue the Service at any time,
				with or without notice. We shall not be liable to you or any third party
				for any modification, suspension, or discontinuance of the Service.
			</p>

			<h2>11. Changes to Terms</h2>
			<p>
				We may modify these Terms at any time by posting the revised Terms on
				the Service. Your continued use of the Service after any changes
				indicates your acceptance of the modified Terms.
			</p>

			<h2>12. Technical Requirements</h2>
			<p>To use the Service, you need:</p>
			<ul>
				<li>A modern web browser with JavaScript enabled</li>
				<li>A stable internet connection</li>
				<li>A device capable of supporting canvas drawing</li>
			</ul>

			<h2>13. Service Availability</h2>
			<p>
				While we strive to maintain high availability, we do not guarantee
				uninterrupted access to the Service. Temporary interruptions may occur
				due to maintenance, updates, or technical issues.
			</p>

			<h2>14. Custom Content</h2>
			<p>When providing custom words for games, you agree not to submit:</p>
			<ul>
				<li>Offensive or inappropriate words</li>
				<li>Trademarked or copyrighted terms without permission</li>
				<li>Personal information</li>
				<li>Deliberately misleading or impossible-to-draw terms</li>
			</ul>

			<h2>15. Termination</h2>
			<p>
				We reserve the right to terminate or suspend access to the Service
				without prior notice for violations of these Terms or for any other
				reason at our discretion.
			</p>

			<h2>16. Governing Law</h2>
			<p>
				These Terms shall be governed by and construed in accordance with the
				laws of the United States, without regard to its conflict of law
				provisions.
			</p>

			<h2>17. Contact Information</h2>
			<p>
				If you have any questions about these Terms, please contact us at
				contact@walagames.com.
			</p>
		</ContentLayout>
	);
}
