import { PolicyLayout } from "@/components/policy-layout";

export function TermsOfService() {
	return (
		<PolicyLayout title="Terms of Service" lastUpdated="November 23, 2024">
			<h2>1. Acceptance of Terms</h2>
			<p>
				By accessing and using the multiplayer drawing game website (the
				"Service") provided by WalaGames ("we," "us," or "our"), you agree to be
				bound by these Terms of Service ("Terms"). If you do not agree to these
				Terms, do not use the Service.
			</p>

			<h2>2. Description of Service</h2>
			<p>
				The Service provides an online multiplayer drawing game platform where
				users can participate in drawing-based activities and communicate with
				other users in temporary game lobbies.
			</p>

			<h2>3. Eligibility</h2>
			<p>
				You must be at least 13 years old to use the Service. By using the
				Service, you represent and warrant that you are at least 13 years of
				age.
			</p>

			<h2>4. User Conduct</h2>
			<p>
				You agree to use the Service in accordance with these Terms and all
				applicable laws. You agree not to:
			</p>
			<ul>
				<li>
					Post or transmit any unlawful, threatening, abusive, hateful,
					defamatory, or otherwise offensive content
				</li>
				<li>
					Violate any third-party rights, including intellectual property rights
				</li>
				<li>Attempt to circumvent any security features of the Service</li>
				<li>Use the Service for any commercial purpose without our consent</li>
				<li>Interfere with or disrupt the Service or servers</li>
				<li>Impersonate any person or entity</li>
			</ul>

			<h2>5. User-Generated Content</h2>
			<h3>5.1 Content Responsibility</h3>
			<p>
				You are solely responsible for any content you create, share, or
				transmit through the Service, including drawings and chat messages. We
				do not claim ownership of your content, but you grant us the right to
				display and transmit it through the Service.
			</p>

			<h3>5.2 Content Disclaimer</h3>
			<p>
				We do not monitor or control user-generated content and are not
				responsible for any content created or shared by users. We are not
				liable for any offensive, inappropriate, or illegal content generated by
				users.
			</p>

			<h2>6. Disclaimers</h2>
			<h3>6.1 Service Provided "As Is"</h3>
			<p>
				The Service is provided on an "as is" and "as available" basis, without
				any warranties of any kind, express or implied.
			</p>

			<h3>6.2 No Liability</h3>
			<p>WalaGames is not liable for any damages arising from:</p>
			<ul>
				<li>Use or inability to use the Service</li>
				<li>Content generated or shared by users</li>
				<li>Technical issues or interruptions in service</li>
				<li>Any unauthorized access to or use of our servers</li>
			</ul>

			<h2>7. Limitation of Liability</h2>
			<p>
				To the maximum extent permitted by law, WalaGames shall not be liable
				for any indirect, incidental, special, consequential, or punitive
				damages arising out of or relating to your use of the Service.
			</p>

			<h2>8. Modifications to Service</h2>
			<p>
				We reserve the right to modify or discontinue the Service at any time,
				with or without notice. We shall not be liable to you or any third party
				for any modification, suspension, or discontinuance of the Service.
			</p>

			<h2>9. Changes to Terms</h2>
			<p>
				We may modify these Terms at any time by posting the revised Terms on
				the Service. Your continued use of the Service after any changes
				indicates your acceptance of the modified Terms.
			</p>

			<h2>10. Governing Law</h2>
			<p>
				These Terms shall be governed by and construed in accordance with the
				laws of [Your Jurisdiction], without regard to its conflict of law
				provisions.
			</p>

			<h2>11. Contact Information</h2>
			<p>
				If you have any questions about these Terms, please contact us at [Your
				Contact Information].
			</p>
		</PolicyLayout>
	);
}
